//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChordsLib.Pages.User_Controls
{


    public partial class Navbar
    {

        /// <summary>
        /// NavbarLogo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChordsLib.Pages.User_Controls.NavbarLogo NavbarLogo;
    }
}
